[log]
level="debug"
as_json=false

[service]
host="https://app.reliably.dev"

[agent]
id="438ff318-93b8-4bb9-b9fe-d65480a173a5"

[organization]
id="8f67bb6a-4944-40af-80b0-921023467cdc"

[plan.providers.github]
enabled=true

[otel]
enabled=true
