name: Run Reliably Experiment

on:
  push:
    paths:
      - "plans/562a1bc4-bda1-41ba-a852-7c67832a9aa7/**"
    branches:
    - main

jobs:
  run-experiment:
    runs-on: ubuntu-latest
    environment: myenv
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --prefer-binary -q -U pip setuptools wheel
        pip install --prefer-binary -U chaostoolkit
        if [[ -f requirements.txt ]]; then
            pip install --prefer-binary --no-cache-dir -r requirements.txt
        fi
        python -c "import chaosreliably.controls.experiment"
    - name: Run experiment
      working-directory: ./plans/562a1bc4-bda1-41ba-a852-7c67832a9aa7
      env:
        RELIABLY_HOST: app.reliably.dev
        RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}
      run : |
        chaos run             --rollback-strategy=always             --journal-path=journal-20220921200517.json             experiment.json
    - name: Store results
      working-directory: ./plans/562a1bc4-bda1-41ba-a852-7c67832a9aa7
      run: |
        mkdir 20220921200517
        mv chaostoolkit.log 20220921200517/chaostoolkit.log
        mv journal-20220921200517.json 20220921200517/journal.json
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add 20220921200517
        git commit -s -m "Plan 562a1bc4-bda1-41ba-a852-7c67832a9aa7 [20220921200517]"
        git pull --rebase origin main
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
