name: Run Agent

on:
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up GCP Authentication
      id: auth
      uses: google-github-actions/auth@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
    - name: Run Reliably CLI
      uses: reliablyhq/actions/agent@main
      with:
        reliably-version: 0.2.2
        github-token: ${{ secrets.GITHUB_TOKEN }}
