name: Run Agent

on:
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run Reliably CLI
      uses: reliablyhq/actions/agent@v0
      with:
        reliably-version: 0.1.10
      env:
        RELIABLY_AGENT_TOKEN: ${{ secrets.RELIABLY_AGENT_TOKEN }}
        OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT }}
        OTEL_EXPORTER_OTLP_TRACES_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_TRACES_HEADERS }}
        OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT }}
