name: Execute a Reliably Plan

on:
  workflow_dispatch:
    inputs:
      reliably-experiment-url:
        description: The full URL to a Reliably experiment
        required: true

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    environment: myenv
    steps:
    - uses: actions/checkout@v3
    - name: Run Reliably CLI
      uses: reliablyhq/actions/plan@v0
      with:
        reliably-agent-token: ${{ secrets.RELIABLY_AGENT_TOKEN }}
        reliably-experiment-url: ${{ inputs.reliably-experiment-url }}
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
