name: Execute a Reliably Plan

on:
  workflow_dispatch:
    inputs:
      experiment-url:
        description: The full URL to a Reliably experiment
        required: true
      environment-name:
        description: The name of the environment to pass secrets
        required: false
      plan-id:
        description: The identifier of the plan which triggered this workflow
        required: false

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment-name }}
    steps:
    - uses: actions/checkout@v3
    - uses: reliablyhq/actions/plan@main
    - run: chaos run --rollback-strategy=always ${{ inputs.experiment-url }}
      env:
        CHAOSTOOLKIT_LOADER_AUTH_BEARER_TOKEN: ${{ secrets.RELIABLY_AGENT_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        RELIABLY_HOST: app.reliably.dev
        RELIABLY_TOKEN: ${{ secrets.RELIABLY_AGENT_TOKEN }}
    - name: Store results
      working-directory: ./plans/${{ inputs.plan_id }}
      run: |
        export NOW=$(date --utc)
        mkdir "${NOW}"
        mv chaostoolkit.log "${NOW}"/chaostoolkit.log
        mv journal-${NOW}.json "${NOW}"/journal.json
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add "${NOW}"
        git commit -s -m "Plan ${{ inputs.plan_id }} [${NOW}]"
        git pull --rebase origin main
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
