name: Execute a Reliably Plan

on:
  workflow_dispatch:
    inputs:
      reliably-experiment-url:
        description: The full URL to a Reliably experiment
        required: true

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    environment: myenv
    steps:
    - uses: actions/checkout@v3
    - name: Install Reliably dependencies
      uses: reliablyhq/actions/plan@main
    - name: Run Reliably Experiment
      run: chaos run --rollback-strategy=always ${{ inputs.reliably-experiment-url }}
      env:
        CHAOSTOOLKIT_LOADER_AUTH_BEARER_TOKEN: ${{ secrets.RELIABLY_AGENT_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
