name: Execute a Reliably Plan

on: workflow_dispatch

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: reliablyhq/actions/plan@main
    - name: Execute Reliably Experiment
      working-directory: ${{ env.basedir }}
      run: chaos run --rollback-strategy=always ${{ env.EXPERIMENT_URL }}
      env:
        CHAOSTOOLKIT_LOADER_AUTH_BEARER_TOKEN: ${{ secrets.RELIABLY_AGENT_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        RELIABLY_TOKEN: ${{ secrets.RELIABLY_AGENT_TOKEN }}
    - name: Store results
      working-directory: ${{ env.basedir }}
      run: |
        export EXECUTION_URL=$(cat journal.json | jq -r '.experiment.extensions[] | select(.name=="reliably") | .execution_url')

        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -s -m "Plan ${{ env.PLAN_ID }}" -m "Visit ${EXECUTION_URL}"
        git pull --rebase origin main
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
