name: Execute a Reliably Plan

on:
  workflow_dispatch:
    inputs:
      reliably-experiment-url:
        description: The full URL to a Reliably experiment
        required: true
      environment-name:
        description: The name of the environment to pass secrets
        required: false
        default: myenv

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment-name }}
    steps:
    - uses: actions/checkout@v3
    - uses: reliablyhq/actions/plan@main
    - run: |
        export PATH=$PATH:./bin
        chaos run --rollback-strategy=always ${{ inputs.reliably-experiment-url }}
      env:
        CHAOSTOOLKIT_LOADER_AUTH_BEARER_TOKEN: ${{ secrets.RELIABLY_AGENT_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
