jobs:
  run-experiment:
    environment: myenv
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: auth
      name: Set up GCP Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - env:
        OTEL_VENDOR: ${{ vars.OTEL_VENDOR }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
      name: Execute Reliably Plan
      uses: reliablyhq/actions/plan@main
      with:
        experiment-url: https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/4556a14b-e776-4cd1-a6b1-c320e06bde2c/raw
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: 8f67bb6a-4944-40af-80b0-921023467cdc
        plan-id: d6b52af8-285e-434e-89b4-b1fcc112ccab
        reliably-experiment-extra: '[{"type":"url","provider":"github","value":"https://github.com/Lawouach/ctkgh/tree/main/plans/d6b52af8-285e-434e-89b4-b1fcc112ccab"}]'
        reliably-host: app.reliably.dev
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/d6b52af8-285e-434e-89b4-b1fcc112ccab
name: Reliably Plan d6b52af8-285e-434e-89b4-b1fcc112ccab
on:
  workflow_dispatch: null
