jobs:
  run-experiment:
    environment: myenv
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: auth
      name: Set up GCP Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - env:
        CLOUDRUN_PROJECT_ID: ${{ vars.CLOUDRUN_PROJECT_ID }}
        CLOUDRUN_SERVICE_NAME: ${{ vars.CLOUDRUN_SERVICE_NAME }}
        OTEL_VENDOR: ${{ vars.OTEL_VENDOR }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
        STACKDRIVER_HOST_PROJECT_ID: ${{ vars.STACKDRIVER_HOST_PROJECT_ID }}
      name: Execute Reliably Plan
      uses: reliablyhq/actions/plan@main
      with:
        experiment-url: https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/11c4ee0f-16ef-44e5-826e-e2644bf4d426/raw
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: 8f67bb6a-4944-40af-80b0-921023467cdc
        plan-id: 0b5b504c-b3d4-4a0a-8e59-b9bb1adad7a9
        reliably-experiment-extra: '[{"type":"url","provider":"github","topic":"commit","value":"https://github.com/Lawouach/ctkgh/tree/main/plans/0b5b504c-b3d4-4a0a-8e59-b9bb1adad7a9"}]'
        reliably-host: app.reliably.dev
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/0b5b504c-b3d4-4a0a-8e59-b9bb1adad7a9
name: Reliably Plan 0b5b504c-b3d4-4a0a-8e59-b9bb1adad7a9
on:
  schedule:
  - cron: '*/10 * * * *'
  workflow_dispatch: null
