name: Run Agent

on:
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up GCP Authentication
      id: auth
      uses: google-github-actions/auth@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
    - name: Execute Reliably Plan
      uses: reliablyhq/actions/plan@main
      env:
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
        OTEL_VENDOR: ${{ vars.OTEL_VENDOR }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
