jobs:
  run-experiment:
    environment: myenv
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: auth
      name: Set up GCP Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - env:
        CLOUDRUN_PROJECT_ID: ${{ vars.CLOUDRUN_PROJECT_ID }}
        CLOUDRUN_SERVICE_NAME: ${{ vars.CLOUDRUN_SERVICE_NAME }}
        OTEL_VENDOR: ${{ vars.OTEL_VENDOR }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
        STACKDRIVER_HOST_PROJECT_ID: ${{ vars.STACKDRIVER_HOST_PROJECT_ID }}
      name: Execute Reliably Plan
      uses: reliablyhq/actions/plan@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: 4e9dc74e-270f-4218-8694-7a1a023c3ed6
        plan-id: d0d0281a-4638-49f2-a4aa-9e14417a8f0b
        reliably-experiment-extra: '[{"type":"url","provider":"github","topic":"commit","value":"https://github.com/Lawouach/ctkgh/tree/main/plans/d0d0281a-4638-49f2-a4aa-9e14417a8f0b"}]'
        reliably-host: 192.168.1.22:8090
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/d0d0281a-4638-49f2-a4aa-9e14417a8f0b
name: Reliably Plan d0d0281a-4638-49f2-a4aa-9e14417a8f0b
on:
  workflow_dispatch: null
