jobs:
  run-experiment:
    environment: myenv
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: auth
      name: Set up GCP Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - env:
        CLOUDRUN_PROJECT_ID: ${{ vars.CLOUDRUN_PROJECT_ID }}
        CLOUDRUN_SERVICE_NAME: ${{ vars.CLOUDRUN_SERVICE_NAME }}
        OTEL_VENDOR: ${{ vars.OTEL_VENDOR }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
        STACKDRIVER_HOST_PROJECT_ID: ${{ vars.STACKDRIVER_HOST_PROJECT_ID }}
      name: Execute Reliably Plan
      uses: reliablyhq/actions/plan@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        org-id: 1f2afd25-419a-40df-aebf-d27af20785f0
        plan-id: 02432af4-2290-4691-a1e9-8024f2b5f423
        reliably-experiment-extra: '[{"type":"url","provider":"github","topic":"commit","value":"https://github.com/Lawouach/ctkgh/tree/main/plans/02432af4-2290-4691-a1e9-8024f2b5f423"}]'
        reliably-host: 192.168.1.16:8090
        reliably-service-token: ${{ secrets.RELIABLY_SERVICE_TOKEN }}
        working-dir: plans/02432af4-2290-4691-a1e9-8024f2b5f423
name: Reliably Plan 02432af4-2290-4691-a1e9-8024f2b5f423
on:
  schedule:
  - cron: '*/1 * * * *'
  workflow_dispatch: null
