jobs:
  run-experiment:
    environment: myenv
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: auth
      name: Set up GCP Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - name: Run Reliably CLI
      uses: reliablyhq/actions/agent@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        reliably-version: 0.2.4
name: Reliably Plan 437481b2-e469-4e3e-a2a6-8a0d325ccab1
on:
  workflow_dispatch: null
