jobs:
  execute-reliably-plan:
    environment: myenv
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: reliablyhq/actions/plan@main
      with:
        experiment-url: https://app.reliably.dev/api/v1/organization/8f67bb6a-4944-40af-80b0-921023467cdc/experiments/4556a14b-e776-4cd1-a6b1-c320e06bde2c/raw
        github-token: ${{ secrets.GITHUB_TOKEN }}
        plan-id: b72d0d2c-cce1-4c9b-8880-c36cde238b44
        reliably-agent-token: ${{ secrets.RELIABLY_AGENT_TOKEN }}
        reliably-experiment-extra: '[{"type":"url","provider":"github","value":"https://github.com/Lawouach/ctkgh/tree/main/plans/b72d0d2c-cce1-4c9b-8880-c36cde238b44"}]'
        reliably-host: app.reliably.dev
        working-dir: plans/b72d0d2c-cce1-4c9b-8880-c36cde238b44
name: Reliably Plan b72d0d2c-cce1-4c9b-8880-c36cde238b44
on:
  workflow_dispatch: {}
